### ISSUE TITLE
Problem Install Plugin on OMV 2.1.2

### ISSUE THREAD

**Issue by sorahunter** [OpenMediaVault-Plugin-Developers/openmediavault-cups#9] opened 2015-07-20 23:34 UTC
Hello,

I contact you because I have a problem with the installation of the plugin cups.

After reinstalment of Openmediavault 2.1.2, I wanted to reinstall cups which fails the installation.

I you joint details of the installation if that can help to solve the problem.

By thanking you.

Thomas.

CODE :

Building dependency tree...

Reading state information...

The following extra packages will be installed:
  hpijs-ppds python-cups python-daemon python-lockfile python-lxml python-pip
  python-setuptools
Suggested packages:
  python-lxml-dbg
Recommended packages:
  python-dev-all build-essential
The following NEW packages will be installed:
  hpijs-ppds openmediavault-cups python-cups python-daemon python-lockfile
  python-lxml python-pip python-setuptools
0 upgraded, 8 newly installed, 0 to remove and 1 not upgraded.
Need to get 2837 kB of archives.
After this operation, 21.0 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  hpijs-ppds python-cups python-lockfile python-daemon python-lxml
  python-setuptools python-pip openmediavault-cups
Authentication warning overridden.
Get:1 http://ftp.fr.debian.org/debian/ wheezy/main hpijs-ppds all 3.12.6-3.1+deb7u1 [847 kB]
Get:2 http://packages.omv-extras.org/debian/ stoneburner/main openmediavault-cups all 1.0.9 [44.4 kB]
Get:3 http://ftp.fr.debian.org/debian/ wheezy/main python-cups amd64 1.9.48-1.1 [117 kB]
Get:4 http://ftp.fr.debian.org/debian/ wheezy/main python-lockfile all 1:0.8-2 [8908 B]
Get:5 http://ftp.fr.debian.org/debian/ wheezy/main python-daemon all 1.5.5-1 [19.9 kB]
Get:6 http://ftp.fr.debian.org/debian/ wheezy/main python-lxml amd64 2.3.2-1+deb7u1 [1238 kB]
Get:7 http://ftp.fr.debian.org/debian/ wheezy/main python-setuptools all 0.6.24-1 [449 kB]
Get:8 http://ftp.fr.debian.org/debian/ wheezy/main python-pip all 1.1-3 [112 kB]
Fetched 2837 kB in 1s (2290 kB/s)
Selecting previously unselected package hpijs-ppds.
(Reading database ...
139595 files and directories currently installed.)
Unpacking hpijs-ppds (from .../hpijs-ppds_3.12.6-3.1+deb7u1_all.deb) ...
Selecting previously unselected package python-cups.
Unpacking python-cups (from .../python-cups_1.9.48-1.1_amd64.deb) ...
Selecting previously unselected package python-lockfile.
Unpacking python-lockfile (from .../python-lockfile_1%3a0.8-2_all.deb) ...
Selecting previously unselected package python-daemon.
Unpacking python-daemon (from .../python-daemon_1.5.5-1_all.deb) ...
Selecting previously unselected package python-lxml.
Unpacking python-lxml (from .../python-lxml_2.3.2-1+deb7u1_amd64.deb) ...
Selecting previously unselected package python-setuptools.
Unpacking python-setuptools (from .../python-setuptools_0.6.24-1_all.deb) ...
Selecting previously unselected package python-pip.
Unpacking python-pip (from .../python-pip_1.1-3_all.deb) ...
Selecting previously unselected package openmediavault-cups.
Unpacking openmediavault-cups (from .../openmediavault-cups_1.0.9_all.deb) ...
Processing triggers for cups ...
Starting Common Unix Printing System: cupsd
.
Updating PPD files for cups-filters ...
Updating PPD files for foomatic-db-compressed-ppds ...
Updating PPD files for foomatic-db-engine ...
Updating PPD files for ghostscript-cups ...
Updating PPD files for hpijs-ppds ...
Updating PPD files for openprinting-ppds ...
Updating PPD files for c2esp ...
Updating PPD files for escpr ...
Updating PPD files for foo2zjs ...
Updating PPD files for hpcups ...
Updating PPD files for hpijs ...
Updating PPD files for m2300w ...
Updating PPD files for postscript-hp ...
Updating PPD files for ptouch ...
Updating PPD files for pxljr ...
Updating PPD files for sag-gdi ...
Updating PPD files for splix ...
Processing triggers for man-db ...
Processing triggers for openmediavault ...
Restarting engine daemon ...
Setting up hpijs-ppds (3.12.6-3.1+deb7u1) ...
Setting up python-cups (1.9.48-1.1) ...
Setting up python-lockfile (1:0.8-2) ...
Setting up python-daemon (1.5.5-1) ...
Setting up python-lxml (2.3.2-1+deb7u1) ...
Setting up python-setuptools (0.6.24-1) ...
Setting up python-pip (1.1-3) ...
Setting up openmediavault-cups (1.0.9) ...
Generating locales (this might take a while)...
  en_US.UTF-8
...
 done
  fr_FR.UTF-8
...
 done
Generation complete.
Restarting Common Unix Printing System: cupsd
.
Downloading/unpacking cloudprint
  Downloading cloudprint-0.13.tar.gz
  Running setup.py egg_info for package cloudprint

Downloading/unpacking requests>=2.7.0 (from cloudprint)
  Running setup.py egg_info for package requests

Downloading/unpacking pycups (from cloudprint)
  Running setup.py egg_info for package pycups

Installing collected packages: cloudprint, requests, pycups
  Running setup.py install for cloudprint

    Installing cloudprint script to /usr/local/bin
  Running setup.py install for requests

  Running setup.py install for pycups
    building 'cups' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-H_QLDC-record/install-record.txt:
    running install

running build

running build_ext

building 'cups' extension

creating build

creating build/temp.linux-x86_64-2.7

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o

unable to execute gcc: No such file or directory

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-H_QLDC-record/install-record.txt failed with error code 1 in /build/pycups
Storing complete log in /root/.pip/pip.log
dpkg: error processing openmediavault-cups (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for python-support ...
Processing triggers for openmediavault ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-cups
Creating index of upgradeable packages ...
Creating index of OpenMediaVault plugins ...
E: Sub-process /usr/bin/dpkg returned an error code (1)
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export LANG=C; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --force-yes --fix-missing --allow-unauthenticated --reinstall install openmediavault-cups 2>&1': Reading package lists...

Building dependency tree...

Reading state information...

**Comment by nohatssir** [comment] 2015-07-20 23:56
Duplicate of #8. This is solved when the next version is released which also comes with ExtJS 5.0 compatibility.

**Comment by sorahunter** [comment] 2015-07-21 00:53
Sorry, I followed the position # 8, and my problem is solved thank you.

**Closed** 2015-07-21 09:47 UTC
Labels: duplicate
